# Generated by Django 5.2.4 on 2025-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
