# Generated by Django 5.2.4 on 2025-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
    ]
