# Generated by Django 5.2.4 on 2025-07-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_image_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
